import './globals.css';
import SessionProviderWrapper from '@/components/SessionProviderWrapper';
import Header from '@/components/Header'; // Import the new Header component
import Footer from '@/components/Footer'; // Import the new Footer component
import MobileNav from '@/components/MobileNav'; // Import MobileNav component
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';

export const metadata = {
  title: 'Toko Monggo',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="id">
      <body>
        <SessionProviderWrapper session={session}>
          <div className="min-h-screen flex flex-col px-0.5 md:px-6">
            <Header /> {/* Use the imported Header component */}
            <main className="flex-grow bg-gray-50">
              {children}
            </main>
            <Footer /> {/* Use the imported Footer component */}
            <MobileNav /> {/* Add Mobile Navigation component */}
          </div>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}